### ISSUE TITLE
specify the directory for the datasets

### ISSUE THREAD

**Issue by Iris-Lynn** [ameliajimenez/curriculum-federated-learning#3]
Your project is really great, but my code ability is a little weak, I ran the following error after running single.py directly, can you give me an example of specifying the data set directory
![image](https://user-images.githubusercontent.com/115773507/234281899-458bb0ef-d478-4fbf-9174-b2a4a166f635.png)

**Comment by ameliajimenez** [comment]
Hi, the code is expected to find a "data" folder in the repository. Apologies I used a private dataset and cannot share the data. The variable `data_path` is found in the `params.py` file, in this file you can find how to specify the dataset directories: lines 42-57.
